spring:
  application: 
    name:
      spring-chat-client
  output.ansi.enabled: ALWAYS
  security:
    oauth2:
      client:
        provider:
          spring:
            issuer-uri: http://localhost:8080
        registration:
          reg-client:
            provider: spring
            client-id: demo-client
            # client-secret: "{noop}ourtopsecretsecret"
            client-secret: "ourtopsecretsecret"
            authorization-grant-type: authorization_code
            # authorization-grant-type: client_credentials
            client-authentication-method: client_secret_basic
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: user.read,openid


server:
  port: 8082